### ISSUE TITLE
转载请求

### ISSUE THREAD

**Issue by BraFei** [LirenW/NUIST_thesis_template_V2.0#1]
同校友，来自南信大，fork转载请求

**Comment by zxdawn** [comment]
@BraFei That's ok. I forked it from another one.

**Comment by LirenW** [comment]
抱歉这么久才看到，本人git不太熟练，fork的话肯定没问题的，不过如果有修改的话个人希望能pull一下requests，我也好改进一下~

**Comment by LirenW** [comment]
> 同校友，来自南信大，fork转载请求

抱歉这么久才看到，本人git不太熟练，fork的话肯定没问题的，不过如果有修改的话个人希望能pull一下requests，我也好改进一下~
